Fix compilation errors introduced by 3.4.80 merge
requires testing

caused by commit:
	slub: Fix calculation of cpu slabs

	error:
		forbidden warning error:
			x may be uninitialized